version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://docker-dind:2376
      - DOCKER_TLS_VERIFY=0
    volumes:
      - jenkins_home:/var/jenkins_home
      - docker-certs:/certs/client:ro
    networks:
      - jenkins-network
    depends_on:
      - docker-dind

  docker-dind:
    image: docker:dind
    container_name: docker-dind
    privileged: true
    ports:
      - "2376:2376"
    volumes:
      - jenkins_home:/var/jenkins_home
      - docker-certs:/certs
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - jenkins-network

volumes:
  jenkins_home:
  docker-certs:

networks:
  jenkins-network:
    driver: bridge
